---
name: Git Back Up
version: 0.0.17
slug: git-back-up
description: Uses Git to back up Config Folder
startup: application
boot: auto
map: 
  - config:rw
url: https://github.com/cpyarger/Home-Assistant-Addons/tree/master/Git-Back-Up
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  include_secrets_file: false
  deployment_key: []
  deployment_key_protocol: rsa
  deployment_password: ""
  deployment_user: ""
  git_branch: main
  git_remote: origin
  repository: null
schema:
  include_secrets_file: bool
  deployment_key:
    - password
  deployment_key_protocol: match(rsa|dsa|ecdsa|ed25519|rsa)
  deployment_password: password
  deployment_user: str
  git_branch: str
  git_remote: str
  repository: str