---
name: Git Back Up
version: 0.0.7
slug: git-back-up
description: Uses Git to back up Config Folder
startup: application
boot: auto
map: 
  - config:rw
url: https://github.com/cpyarger/Home-Assistant-Addons/tree/master/Git-Back-Up
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  git_url: ""
  git_rsa_kay: ""
  home_assistant_config_enable: true
  esphome_config_enable: true
schema:
  git_url: str
  git_rsa_kay: password
  home_assistant_config_enable: bool
  esphome_config_enable: bool

