---
version: 0.0.4
slug: googledomainsdns
name: Google Domains Dynamic DNS
description: >-
  Dynamic DNS (DynDNS or DDNS) service via Google Domains with Let's Encrypt support
url: https://github.com/cpyarger/Home-Assistant-Addons/tree/master/GoogleDomainsDNS
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - ssl:rw
options:
  domain: ""
  username: ""
  password: ""
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
  token: null
schema:
  domain: str
  username: str
  password: password
  ipv4: str?
  ipv6: str?
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
  seconds: int
startup: services
