---
name: RTLAMR to HA REST API
version: 0.7.33
slug: rtlamr
description: RF to Home Assistant REST API Bridge based on RTL_SDR/RTL_433 for RTL2832U based DVB-T USB tuners
startup: application
boot: auto
homeassistant_api: True
auth_api: True
map: 
  - config:rw 
  - ssl
url: https://github.com/cpyarger/Home-Assistant-Addons/tree/master/RTLAMR-2-HA
usb: true
host_network: False
arch: 
  - aarch64
  - amd64
  - armv7
  - i386
options:
  debug: False
  msgType: scm
  ids: ""
  duration: 15
  pause_time: 30
  scm_plus_gas_divisor: 1
schema:
  debug: bool
  msgType: list(scm|scm+|scm+,r900|idm|netidm|r900|r900bcd|all)
  ids: str?
  duration: int
  pause_time: int
  scm_plus_gas_divisor: int?


